<?php

namespace Database\Seeders\dbseeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FamilyDetailSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('family_details')->insert([
            [
                'about_family' => 'We belong to a well-cultured middle-class joint family with strong traditional values.',
                'brothers_count' => 2,
                'brothers_married' => 1,
                'family_status' => 'middle class',
                'family_type' => 'joint',
                'family_values' => 'traditional',
                'father_name' => 'Ramesh Kumar',
                'father_occupation' => 'Businessman',
                'father_vangusam' => 'Rajput',
                'mother_name' => 'Sita Devi',
                'mother_occupation' => 'Homemaker',
                'mother_vangusam' => 'Brahmin',
                'profile_id' => 1,
                'property_description' => 'Own house with 3 bedrooms, small garden and parking space.',
                'sisters_count' => 1,
                'sisters_married' => 0,
                'soveran_details' => 1,
                'surname' => 'Kumar',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'about_family' => 'Educated nuclear family, progressive outlook with modern values.',
                'brothers_count' => 0,
                'brothers_married' => 0,
                'family_status' => 'upper',
                'family_type' => 'nuclear',
                'family_values' => 'modern',
                'father_name' => 'Mahesh Patel',
                'father_occupation' => 'Engineer',
                'father_vangusam' => null,
                'mother_name' => 'Kiran Patel',
                'mother_occupation' => 'Teacher',
                'mother_vangusam' => null,
                'profile_id' => 2,
                'property_description' => null,
                'sisters_count' => 2,
                'sisters_married' => 2,
                'soveran_details' => 54,
                'surname' => 'Patel',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'about_family' => 'Medical family with strong educational background.',
                'brothers_count' => 1,
                'brothers_married' => 0,
                'family_status' => 'upper middle class',
                'family_type' => 'nuclear',
                'family_values' => 'traditional',
                'father_name' => 'Raj Sharma',
                'father_occupation' => 'Doctor',
                'father_vangusam' => 'Brahmin',
                'mother_name' => 'Priya Sharma',
                'mother_occupation' => 'Nurse',
                'mother_vangusam' => 'Brahmin',
                'profile_id' => 3,
                'property_description' => null,
                'sisters_count' => 0,
                'sisters_married' => 0,
                'soveran_details' => null,
                'surname' => 'Sharma',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'about_family' => 'Disciplined family with military background and strong values.',
                'brothers_count' => 3,
                'brothers_married' => 2,
                'family_status' => 'middle class',
                'family_type' => 'joint',
                'family_values' => 'traditional',
                'father_name' => 'Vikram Singh',
                'father_occupation' => 'Army Officer',
                'father_vangusam' => 'Kshatriya',
                'mother_name' => 'Sunita Singh',
                'mother_occupation' => 'Homemaker',
                'mother_vangusam' => 'Kshatriya',
                'profile_id' => 4,
                'property_description' => null,
                'sisters_count' => 1,
                'sisters_married' => 1,
                'soveran_details' => null,
                'surname' => 'Singh',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'about_family' => 'Well-established business family with modern outlook.',
                'brothers_count' => 1,
                'brothers_married' => 1,
                'family_status' => 'upper',
                'family_type' => 'nuclear',
                'family_values' => 'modern',
                'father_name' => 'Anil Gupta',
                'father_occupation' => 'Chartered Accountant',
                'father_vangusam' => null,
                'mother_name' => 'Ritu Gupta',
                'mother_occupation' => 'Bank Manager',
                'mother_vangusam' => null,
                'profile_id' => 5,
                'property_description' => null,
                'sisters_count' => 1,
                'sisters_married' => 0,
                'soveran_details' => null,
                'surname' => 'Gupta',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'about_family' => 'Academic family focused on education and cultural values.',
                'brothers_count' => 0,
                'brothers_married' => 0,
                'family_status' => 'middle class',
                'family_type' => 'nuclear',
                'family_values' => 'traditional',
                'father_name' => 'Mohan Joshi',
                'father_occupation' => 'Professor',
                'father_vangusam' => 'Brahmin',
                'mother_name' => 'Kavita Joshi',
                'mother_occupation' => 'Principal',
                'mother_vangusam' => 'Brahmin',
                'profile_id' => 6,
                'property_description' => null,
                'sisters_count' => 3,
                'sisters_married' => 1,
                'soveran_details' => null,
                'surname' => 'Joshi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'about_family' => 'Agricultural family with deep roots in farming and traditional lifestyle.',
                'brothers_count' => 2,
                'brothers_married' => 0,
                'family_status' => 'middle class',
                'family_type' => 'joint',
                'family_values' => 'traditional',
                'father_name' => 'Krishna Reddy',
                'father_occupation' => 'Farmer',
                'father_vangusam' => 'Reddy',
                'mother_name' => 'Lakshmi Reddy',
                'mother_occupation' => 'Homemaker',
                'mother_vangusam' => 'Reddy',
                'profile_id' => 7,
                'property_description' => 'Farmland and ancestral home in village.',
                'sisters_count' => 2,
                'sisters_married' => 1,
                'soveran_details' => null,
                'surname' => 'Reddy',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}