<?php

return [
    'required_fields' => [
        'profile' => [
            'gender',
            'marital_status',
            'education',
            'occupation',
            'height',
            'weight',
            'country',
            'state',
            'city',
        ],
        'family_detail' => [
            'father_name',
            'mother_name',
            'father_vangusam',
            'mother_vangusam',
            'family_type',
            'brothers_count',
            'sisters_count',
        ],
        'partner_preference' => [
            'age',
            'height',
            'weight',
            'physical_status',
            'marital_status',
            'education',
            'profession',
            'body_type',
            'expectations',
        ],
    ],
    'field_labels' => [
        'gender' => 'Gender',
        'marital_status' => 'Marital Status',
        'education' => 'Education',
        'occupation' => 'Occupation',
        'height' => 'Height',
        'weight' => 'Weight',
        'country' => 'Country',
        'state' => 'State',
        'city' => 'City',
        'father_name' => 'Father Name',
        'mother_name' => 'Mother Name',
        'father_vangusam' => 'Father Vangusam',
        'mother_vangusam' => 'Mother Vangusam',
        'family_type' => 'Family Type',
        'brothers_count' => 'Brothers Count',
        'sisters_count' => 'Sisters Count',
        'age' => 'Preferred Age',
        'physical_status' => 'Physical Status',
        'profession' => 'Profession',
        'body_type' => 'Body Type',
        'expectations' => 'Expectations',
    ],
];