<?php

return [
    'general' => [
        [
            'en_q' => 'I have not registered yet, will i be able to login?',
            'ta_q' => 'நான் இன்னும் பதிவு செய்யவில்லை, நான் உள்நுழைய முடியுமா?',
            'en_a' => 'No, Only registered users will be able to login.',
            'ta_a' => 'இல்லை, பதிவுசெய்த பயனர்கள் மட்டுமே உள்நுழைய முடியும்.',
        ],
        [
            'en_q' => 'I have registered now, will i be able to login?',
            'ta_q' => 'நான் இப்போது பதிவு செய்துள்ளேன், நான் உள்நுழைய முடியுமா?',
            'en_a' => 'Yes, by providing the username (registered mobile number) and password you will be able to login.',
            'ta_a' => 'ஆம், பயனர்பெயர் (பதிவு செய்யப்பட்ட மொபைல் எண்) மற்றும் கடவுச்சொல்லை வழங்குவதன் மூலம் நீங்கள் உள்நுழைய முடியும்.',
        ],
        [
            'en_q' => 'What is the working days and hours of forum?',
            'ta_q' => 'மன்றத்தின் வேலை நாட்கள் மற்றும் வேலைநேரம் என்ன?',
            'en_a' => 'Forum will be working on all Fridays and no moon days.',
            'ta_a' => 'அனைத்து வெள்ளிக்கிழமைகளிலும், அமாவாசை நாட்களிலும் மன்றம் செயல்படும்.',
        ],
        [
            'en_q' => 'Will i be able to view the profiles without paying the registration fee?',
            'ta_q' => 'பதிவுக் கட்டணத்தை செலுத்தாமல் சுயவிவரங்களைக் காண முடியுமா?',
            'en_a' => 'No, you have to register your profile by paying the registration fee to search and view other profiles.',
            'ta_a' => 'இல்லை, பிற சுயவிவரங்களைத் தேடவும் பார்க்கவும் பதிவு கட்டணத்தை செலுத்தி உங்கள் சுயவிவரத்தை பதிவு செய்ய வேண்டும்.',
        ],
        [
            'en_q' => 'How do i register my profile?',
            'ta_q' => 'எனது சுயவிவரத்தை எவ்வாறு பதிவு செய்வது?',
            'en_a' => 'Registration can be done in two different ways: Offline registration or Online registration.',
            'ta_a' => 'பதிவு இரண்டு வெவ்வேறு வழிகளில் செய்யப்படலாம்: I. ஆஃப்லைன் பதிவு. II. ஆன்லைன் பதிவு.',
        ],
        [
            'en_q' => 'What is the difference between offline and online registration?',
            'ta_q' => 'ஆஃப்லைன் மற்றும் ஆன்லைன் பதிவுக்கு என்ன வித்தியாசம்?',
            'en_a' => 'Offline registered members will be able to see only short profile view and will not be able to avail any other features available on the website. Online registered members will be able to see detailed profile view and allowed to take profile print. Also will be able to avail all the features available on the website.',
            'ta_a' => 'ஆஃப்லைனில் பதிவுசெய்த உறுப்பினர்கள் குறுகிய சுயவிவரக் காட்சியை மட்டுமே காண முடியும் மற்றும் இணையதளத்தில் கிடைக்கும் வேறு எந்த அம்சங்களையும் பெற முடியாது. ஆன்லைன் பதிவு செய்த உறுப்பினர்கள் விரிவான சுயவிவரக் காட்சியைக் காண முடியும் மற்றும் சுயவிவர அச்சு எடுக்க அனுமதிக்கப்படுவார்கள். இணையதளத்தில் கிடைக்கும் அனைத்து அம்சங்களையும் பெற முடியும்.',
        ],
        [
            'en_q' => 'I have registered my profile a month back, will i be able to update now?',
            'ta_q' => 'என் சுயவிபரத்தை ஒரு மாதத்திற்க்கு முன் பதிவு செய்தேன். தற்போது அதை திருத்த முடியுமா?',
            'en_a' => 'No, you cannot update the profile after 7 days from the date of registration.',
            'ta_a' => 'பதிவுசெய்த நாளிலிருந்து 7 நாட்களுக்குள் நீங்கள் சுயவிவரத்தை திருத்த முடியும். அதற்க்கு பிறகு முடியாது.',
        ],
        [
            'en_q' => 'Will i be able to do auto renewal, before my profile gets de-activated?',
            'ta_q' => 'எனது சுயவிவரம் செயலிழக்கப்படுவதற்கு முன்பு, தானாக புதுப்பித்தலை என்னால் செய்ய முடியுமா?',
            'en_a' => 'No, currently auto renewal option is not available. However you will be notified 3 days earlier about the expiry date via SMS & Email, so that you can renew it before your profile gets deactivated.',
            'ta_a' => 'இல்லை, தற்போது தானாக புதுப்பிக்கும் வசதி இல்லை. என்றாலும், காலாவதி தேதி குறித்து 3 நாட்களுக்கு முன்பே உங்களுக்கு எஸ்எம்எஸ் மற்றும் மின்னஞ்சல் வழியாக அறிவிப்பு கிடைக்கும், இதனால் உங்கள் சுயவிவரம் செயலிழக்கப்படுவதற்கு முன்பு அதை நீங்கள் புதுப்பிக்க முடியும்.',
        ],
        [
            'en_q' => 'How can i change my password?',
            'ta_q' => 'எனது கடவுச்சொல்லை எவ்வாறு மாற்றுவது?',
            'en_a' => 'By using the change password icon in the left corner of the profile page, you will be able to change your password.',
            'ta_a' => 'சுயவிவரப் பக்கத்தின் இடது மூலையில் உள்ள கடவுச்சொல் மாற்றும் ஐகானைப் பயன்படுத்துவதன் மூலம், உங்கள் கடவுச்சொல்லை மாற்ற முடியும்.',
        ],
        [
            'en_q' => 'What i have to do if i have forgot my password?',
            'ta_q' => 'எனது கடவுச்சொல்லை மறந்துவிட்டால் நான் என்ன செய்ய வேண்டும்?',
            'en_a' => 'By clicking the forgot password in the login page, your registered password will be sent via SMS and mail to the registered mobile number and mail ID.',
            'ta_a' => 'உள்நுழைவு பக்கத்தில் கடவுச்சொல்லை மீட்டேடுக்கும் ஐகானை கிளிக் செய்வதன் மூலம், உங்கள் பதிவு செய்யப்பட்ட கடவுச்சொல் எஸ்எம்எஸ் மற்றும் மின்அஞ்சல் வழியாக பதிவு செய்யப்பட்ட மொபைல் எண்ணுக்கு அனுப்பப்படும்.',
        ],
        [
            'en_q' => 'How do i search for a profile?',
            'ta_q' => 'நான் சுயவிவரத்தை எவ்வாறு தேடுவது?',
            'en_a' => 'By using the search tab in the Active member page, you can search for your match based on your search criteria.',
            'ta_a' => 'செயலியில் உள்ள உறுப்பினர் பக்கத்தில் தேடும் தாவலைப் பயன்படுத்துவதன் மூலம், உங்கள் தேடல் அளவுகோலின் அடிப்படையில் உங்களுக்கு பொருத்தமானதை தேடலாம்.',
        ],
        [
            'en_q' => 'How to log out?',
            'ta_q' => 'வெளியேறுவது எப்படி?',
            'en_a' => 'Click the log out tab which appears on top right corner of the page to log out from your profile.',
            'ta_a' => 'உங்கள் சுயவிவரத்திலிருந்து வெளியேற பக்கத்தின் மேல் வலது மூலையில் தோன்றும் வெளியேறு தாவலைக் கிளிக் செய்க.',
        ],
        [
            'en_q' => 'Can i register for my son/daughter/friend/sibling in this site?',
            'ta_q' => 'இந்த தளத்தில் எனது மகன் / மகள் / நண்பர் / உடன்பிறப்புக்காக பதிவு செய்யலாமா?',
            'en_a' => 'Yes, you can register for your son/daughter, friend and your siblings in our site.',
            'ta_a' => 'ஆம், உங்கள் மகன் / மகள், நண்பர் மற்றும் உங்கள் உடன்பிறப்புகளுக்கு எங்கள் தளத்தில் பதிவு செய்யலாம்.',
        ],
        [
            'en_q' => 'What are the payment options available in the site for online registration?',
            'ta_q' => 'ஆன்லைன் பதிவுக்கு கட்டணம் எவ்வாறு செலுத்தலாம்?',
            'en_a' => 'We have most of the payment modes like credit card, debit card and net banking.',
            'ta_a' => 'கிரெடிட் கார்டு, டெபிட் கார்டு மற்றும் நெட் பேங்கிங் போன்ற கட்டண முறைகளில் செலுத்தலாம்.',
        ],
        [
            'en_q' => 'How long will i be able to use my account after successful registration?',
            'ta_q' => 'வெற்றிகரமான பதிவுக்குப் பிறகு எவ்வளவு காலம் எனது கணக்கைப் பயன்படுத்த முடியும்?',
            'en_a' => 'Based on the successful registration, your account is valid for either six months or 100 profile views, whichever is satisfied first — after that your profile will be deactivated automatically.',
            'ta_a' => 'வெற்றிகரமான பதிவின் அடிப்படையில், உங்கள் கணக்கு ஆறு மாதங்கள் அல்லது 100 சுயவிவரக் காட்சிகளுக்கு செல்லுபடியாகும். இதில் எது முதலில் நடைபெறுகிறதோ அப்போது உங்கள் பதிவு செயலிலக்கும்.',
        ],
        [
            'en_q' => 'If i want to use my account more than 6 months or 100 profile views, what should i do?',
            'ta_q' => 'எனது கணக்கை 6 மாதங்கள் அல்லது 100 சுயவிவரக் காட்சியை தாண்டி பயன்படுத்த விரும்பினால், நான் என்ன செய்ய வேண்டும்?',
            'en_a' => 'By renewing your account you can extend your profile activation for next 6 months or 100 profile views.',
            'ta_a' => 'உங்கள் கணக்கைப் புதுப்பிப்பதன் மூலம் உங்கள் சுயவிவர செயல்பாட்டை அடுத்த 6 மாதங்கள் அல்லது 100 சுயவிவரக் காட்சிக்கு நீட்டிக்க முடியும்.',
        ],
        [
            'en_q' => 'What should i do to make my profile appear in home page?',
            'ta_q' => 'எனது சுயவிவரம் முகப்பு பக்கத்தில் தோன்றுவதற்கு நான் என்ன செய்ய வேண்டும்?',
            'en_a' => 'By uploading your profile picture you can make your profile visible to others in the home page.',
            'ta_a' => 'உங்கள் சுயவிவரப் படத்தைப் பதிவேற்றுவதன் மூலம் உங்கள் சுயவிவரத்தை முகப்புப் பக்கத்தில் மற்றவர்களுக்குத் தெரியப்படுத்தலாம்.',
        ],
        [
            'en_q' => 'What are the search options available to search for the best profile?',
            'ta_q' => 'சிறந்த சுயவிவரத்தைத் தேட கிடைக்கக்கூடிய தேடல் வாய்ப்புக்கள் யாவை?',
            'en_a' => 'You can search for the best profile based on: Father\'s Vangusam, Educational qualification, Age, Height, Marital status, and Star.',
            'ta_a' => 'கீழே உள்ள வடிப்பான்களின் அடிப்படையில் சிறந்த சுயவிவரத்தை நீங்கள் தேடலாம்: தந்தையின் வங்குசம், கல்வித் தகுதி, வயது, உயரம், திருமண நிலை மற்றும் நட்சத்திரம்.',
        ],
        [
            'en_q' => 'Can I choose my own Matrimony ID?',
            'ta_q' => 'எனது சொந்த மேட்ரிமோனி ஐடியை நான் தேர்வு செய்யமுடியுமா?',
            'en_a' => 'Every Matrimony ID is unique and is allocated by the system. You cannot choose your own Matrimony ID since it is system generated and cannot be changed under any circumstance.',
            'ta_a' => 'ஒவ்வொரு மேட்ரிமோனி ஐடியும் தனித்துவமானது மற்றும் கணினியால் ஒதுக்கப்படுகிறது. உங்கள் சொந்த மேட்ரிமோனி ஐடியை நீங்கள் தேர்வு செய்ய முடியாது, ஏனெனில் இது கணினியால் உருவாக்கப்பட்டது மற்றும் எந்த சூழ்நிலையிலும் மாற்ற முடியாது.',
        ],
        [
            'en_q' => 'I have not completed my registration either in offline or in online, will my profile be visible to others in the search result?',
            'ta_q' => 'நான் எனது பதிவை ஆஃப்லைனிலோ அல்லது ஆன்லைனிலோ முடிக்கவில்லை, எனில் எனது சுயவிவரம் மற்றவருக்குத் தெரியுமா?',
            'en_a' => 'No, until your profile is registered successfully either in offline or in online, your profile will not be visible in the search list of the other members.',
            'ta_a' => 'இல்லை, உங்கள் சுயவிவரம் ஆஃப்லைனில் அல்லது ஆன்லைனில் வெற்றிகரமாக பதிவு செய்யப்படும் வரை, உங்கள் சுயவிவரம் மற்ற உறுப்பினர்களின் தேடல் பட்டியலில் காணப்படாது.',
        ],
    ],

    'online' => [
        [
            'en_q' => 'How can i register successfully in online?',
            'ta_q' => 'ஆன்லைனில் வெற்றிகரமாக பதிவு செய்வது எப்படி?',
            'en_a' => 'By clicking the register tab in the home page, you can register. However to complete the registration successfully, you have to update your profile details by paying the registration fee.',
            'ta_a' => 'முகப்பு பக்கத்தில் உள்ள பதிவு தாவலைக் கிளிக் செய்வதன் மூலம், நீங்கள் பதிவு செய்ய முடியும், ஆனால் பதிவை வெற்றிகரமாக முடிக்க, பதிவு கட்டணத்தை செலுத்துவதன் மூலம் உங்கள் முழுமையான சுயவிவரத்தை பதிவு செய்ய வேண்டும்.',
        ],
        [
            'en_q' => 'How can i pay for the online registration?',
            'ta_q' => 'ஆன்லைன் பதிவுக்கு நான் எவ்வாறு பணம் செலுத்த முடியும்?',
            'en_a' => 'You can pay using your credit card, debit card and online banking.',
            'ta_a' => 'உங்கள் கிரெடிட் கார்டு, டெபிட் கார்டு மற்றும் ஆன்லைன் வங்கி பரிவர்தனை ஆகியவற்றைப் பயன்படுத்தி பணம் செலுத்தலாம்.',
        ],
        [
            'en_q' => 'What to do if i don\'t have any of the payment options?',
            'ta_q' => 'எனக்கு பணம் செலுத்தும் வாய்ப்புகள் எதுவும் இல்லையென்றால் என்ன செய்வது?',
            'en_a' => 'Either contact the forum with the help of the contact details available in the site or you can visit our forum directly during the working days.',
            'ta_a' => 'தளத்தில் கிடைக்கும் தொடர்பு விவரங்களின் உதவியுடன் மன்றத்தைத் தொடர்பு கொள்ளுங்கள் அல்லது வேலை நாட்களில் எங்கள் மன்றத்தை நேரடியாகப் பார்வையிடலாம்.',
        ],
        [
            'en_q' => 'What should I enter in the profile description field?',
            'ta_q' => 'சுயவிவர விளக்க புலத்தில் நான் எதை குறிக்க வேண்டும்?',
            'en_a' => 'Your profile description is where you reveal yourself — your personality, likes and dislikes, educational and family background, career and personal interests, and expectations about your partner. Try to give a clear self-description and a complete picture of what you expect. A good description will always fetch instant responses.',
            'ta_a' => 'உங்கள் சுயவிவர விளக்கம் நீங்கள் உங்களை வெளிப்படுத்தும் இடமாகும் - உங்கள் ஆளுமை, விருப்பு வெறுப்புகள், கல்வி மற்றும் குடும்ப பின்னணி, தொழில் மற்றும் தனிப்பட்ட ஆர்வங்கள் மற்றும் உங்கள் கூட்டாளரைப் பற்றிய எதிர்பார்ப்புகள். தெளிவான சுய விளக்கத்தையும் நீங்கள் எதிர்பார்க்கும் முழுமையான விபரங்களை கொடுக்க முயற்சிக்கவும். ஒரு நல்ல விளக்கம் எப்போதும் உடனடி பதில்களைப் பெறும்.',
        ],
        [
            'en_q' => 'I have registered my profile in online, how can I contact other members?',
            'ta_q' => 'ஆன்லைனில் பதிவு செய்துள்ளேன், மற்ற உறுப்பினர்களை எவ்வாறு தொடர்பு கொள்ளலாம்?',
            'en_a' => 'You will be able to contact other members with multiple options — by showing your interest, by sending a message, or directly by using the provided contact details.',
            'ta_a' => 'உங்கள் ஆர்வத்தைக் காண்பிப்பதன் மூலமாகவோ அல்லது செய்தியை அனுப்புவதன் மூலமாகவோ அல்லது வழங்கப்பட்ட தொடர்பு விவரங்களைப் பயன்படுத்துவதன் மூலமாகவோ பல வாய்ப்புகள் மூலம் உங்கள் சக உறுப்பினர்களை நீங்கள் தொடர்பு கொள்ள முடியும்.',
        ],
        [
            'en_q' => 'What is messaging?',
            'ta_q' => 'செய்தி அனுப்புவது என்றால் என்ன?',
            'en_a' => 'You can chat with other members to understand better about them, by clicking the messaging tab and selecting the user from the contact list to start chatting.',
            'ta_a' => 'செய்தியிடல் தாவலைக் கிளிக் செய்வதன் மூலம், மற்ற உறுப்பினர்களுடன் உரையாடலாம் மற்றும் உரையாடலை தொடங்க தொடர்பு பட்டியலிலிருந்து பயனரைத் தேர்ந்தெடுக்கவும்.',
        ],
        [
            'en_q' => 'I am not able to see the profile which i would like to chat in the contact list?',
            'ta_q' => 'தொடர்பு பட்டியலில் நான் உரையாட விரும்பும் சுயவிவரத்தை என்னால் பார்க்க முடியவில்லை?',
            'en_a' => 'You have to click on "Enable messaging" on the match profile to add them in the contact list.',
            'ta_a' => 'தொடர்பு பட்டியலில் அவற்றைச் சேர்க்க மேட்ச் சுயவிவரத்தில் செய்தியிடலை இயக்கு என்பதைக் கிளிக் செய்ய வேண்டும்.',
        ],
        [
            'en_q' => 'Is there a limit on adding the profile to messaging contact list?',
            'ta_q' => 'செய்தி தொடர்பு பட்டியலில் உறுப்பினரைச் சேர்ப்பதற்கு வரம்பு உள்ளதா?',
            'en_a' => 'Yes, you are limited to 10 profiles in the messaging contact list.',
            'ta_a' => 'ஆம், செய்தி தொடர்பு பட்டியலில் சேர்க்க 10 உறுப்பினர்களுடன் நீங்கள் வரையறுக்கப்பட்டுள்ளீர்கள்.',
        ],
        [
            'en_q' => 'I have sent a message but I am not getting any response?',
            'ta_q' => 'நான் செய்தி அனுப்பியிருக்கிறேன், ஆனால் எனக்கு எந்த பதிலும் கிடைக்கவில்லையெனில் என்ன செய்வது?',
            'en_a' => 'Either the opposite member might not have seen your message or they might be an offline registered member.',
            'ta_a' => 'ஒன்று எதிர் உறுப்பினர் உங்கள் செய்தியைக் காணவில்லை அல்லது அவர்கள் ஆஃப்லைனில் பதிவுசெய்யப்பட்ட உறுப்பினராக இருக்கலாம்.',
        ],
        [
            'en_q' => 'What is Express Interest?',
            'ta_q' => 'ஆர்வம் வெளிப்படுத்துவது என்றால் என்ன?',
            'en_a' => 'If you like any profile in the site, you can express interest to let your match know that you are interested in their profile. To send interest: Open the member\'s profile → Express Interest.',
            'ta_a' => 'தளத்தின் எந்த சுயவிவரத்தை நீங்கள் விரும்பினால், நீங்கள் உங்கள் ஆர்வத்தை வெளிப்படுத்தலாம். ஒரு உறுப்பினருக்கு ஆர்வம் வெளிபடுத்த: உறுப்பினரின் சுயவிவரத்தைத் திறக்கவும் → ஆர்வத்தை வெளிப்படுத்தவும்.',
        ],
        [
            'en_q' => 'Is there a limit on Expressing Interest?',
            'ta_q' => 'ஆர்வத்தை வெளிப்படுத்த வரம்பு உள்ளதா?',
            'en_a' => 'Yes, you can express interest to 10 profiles.',
            'ta_a' => 'ஆம், நீங்கள் விரும்பும் 10 சுயவிவரங்களுக்கு ஆர்வத்தை வெளிப்படுத்தலாம்.',
        ],
        [
            'en_q' => 'How to know whether match has accepted my interest?',
            'ta_q' => 'எதிர்தரப்பினர் எனது ஆர்வத்தை ஏற்றுக்கொண்டார்களா என்பதை எப்படி அறிவது?',
            'en_a' => 'You will get notified whether they have accepted or declined your request.',
            'ta_a' => 'அவர்கள் உங்கள் கோரிக்கையை ஏற்றுக்கொண்டார்களா அல்லது நிராகரித்தார்களா என்பது உங்களுக்கு அறிவிக்கப்படும்.',
        ],
        [
            'en_q' => 'How many photos can i upload?',
            'ta_q' => 'நான் எத்தனை புகைப்படங்களை பதிவேற்ற முடியும்?',
            'en_a' => 'You can upload multiple pictures (each picture is restricted to the allowed upload size) until your profile is closed.',
            'ta_a' => 'உங்கள் சுயவிவரம் மூடப்படும் வரை உங்கள் விருப்பத்திற்கு ஏற்ப பல படங்களை பதிவேற்றலாம் (ஒவ்வொரு படமும் அனுமதிக்கப்பட்ட பதிவேற்ற அளவிற்கு கட்டுப்படுத்தப்படும்).',
        ],
        [
            'en_q' => 'How to shortlist the profiles in which I am interested?',
            'ta_q' => 'நான் ஆர்வமுள்ள சுயவிவரங்களை எவ்வாறு பட்டியலிடுவது?',
            'en_a' => 'By clicking the shortlist tab below the individual profile you can shortlist them.',
            'ta_a' => 'தனிப்பட்ட சுயவிவரத்திற்கு கீழே உள்ள குறுகிய பட்டியல் தாவலைக் கிளிக் செய்வதன் மூலம் அவற்றை குறுகிய பட்டியலிடலாம்.',
        ],
        [
            'en_q' => 'When do i get the contact address of my match?',
            'ta_q' => 'நான் விரும்பும் வரணின் தொடர்பு முகவரி எப்போது கிடைக்கும்?',
            'en_a' => 'You can get their contact address or mobile number by printing their profile.',
            'ta_a' => 'அவர்களின் சுயவிவரத்தை அச்சிடுவதன் மூலம் அவர்களின் தொடர்பு முகவரி அல்லது மொபைல் எண்ணைப் பெறலாம்.',
        ],
        [
            'en_q' => 'How to ignore a member who has shown interest?',
            'ta_q' => 'ஆர்வத்தை வெளிப்படுத்திய உறுப்பினரை புறக்கணிப்பது எப்படி?',
            'en_a' => 'If you like to ignore a profile you are not interested in: Open All Members → click the ignore button below the short view of the profile.',
            'ta_a' => 'நீங்கள் ஆர்வமில்லாத சுயவிவரத்தை புறக்கணிக்க: அனைத்து உறுப்பினர்களையும் திறக்கவும் → பிறரின் சுயவிவரத்தின் குறுகிய பார்வைக்கு கீழே உள்ள புறக்கணிப்பு பொத்தானைக் கிளிக் செய்க.',
        ],
        [
            'en_q' => 'I came across a fake profile. How do I report it?',
            'ta_q' => 'நான் ஒரு போலி சுயவிவரத்தைக் கண்டேன். அதை எவ்வாறு புகாரளிப்பது?',
            'en_a' => 'To report a fake profile, click the report tab which is available on the left side in the profile view page.',
            'ta_a' => 'போலி சுயவிவரத்தைப் புகாரளிக்க, சுயவிவரக் காட்சி பக்கத்தில் இடது பக்கத்தில் கிடைக்கும் அறிக்கை தாவலைக் கிளிக் செய்க.',
        ],
        [
            'en_q' => 'How do I view a particular profile?',
            'ta_q' => 'ஒரு குறிப்பிட்ட சுயவிவரத்தை நான் எவ்வாறு பார்ப்பது?',
            'en_a' => 'You can search and view a particular profile by entering the Member ID in the "Search by ID" option.',
            'ta_a' => '"ஐடி மூலம் தேடு" வாய்ப்பில் உறுப்பினர் ஐடியை உள்ளிட்டு ஒரு குறிப்பிட்ட சுயவிவரத்தை நீங்கள் தேடலாம் மற்றும் பார்க்கலாம்.',
        ],
        [
            'en_q' => 'I get the error "No matching records found" while searching for profiles. Why?',
            'ta_q' => 'சுயவிவரங்களைத் தேடும்போது "பொருந்தக்கூடிய பதிவுகள் எதுவும் கிடைக்கவில்லை" என்ற தகவலை பெறுகிறேன். அது ஏன்?',
            'en_a' => 'Please check your search criteria when you receive this message. If you are searching for a particular sub-caste, try rephrasing your spellings.',
            'ta_a' => 'இந்த செய்தியைப் பெறும்போது உங்கள் தேடல் அளவுகோல்களைச் சரிபார்க்கவும். நீங்கள் ஒரு குறிப்பிட்ட துணை சாதியைத் தேடுகிறீர்களானால், உங்கள் எழுத்துப்பிழைகளை மறுவடிவமைக்க முயற்சிக்கவும்.',
        ],
        [
            'en_q' => 'How to deactivate profile?',
            'ta_q' => 'சுயவிவரத்தை எவ்வாறு செயலிழக்கச் செய்வது?',
            'en_a' => 'Click the close account button in the profile page to deactivate your account.',
            'ta_a' => 'உங்கள் கணக்கை செயலிழக்க சுயவிவர பக்கத்தில் உள்ள கணக்கு மூடு பொத்தானைக் கிளிக் செய்க.',
        ],
        [
            'en_q' => 'Can i reopen my account?',
            'ta_q' => 'எனது கணக்கை மீண்டும் திறக்க முடியுமா?',
            'en_a' => 'Yes, you can reopen your account by clicking the open option in your profile page.',
            'ta_a' => 'ஆம், உங்கள் சுயவிவர பக்கத்தில் திறந்த விருப்பத்தை கிளிக் செய்வதன் மூலம் உங்கள் கணக்கை மீண்டும் திறக்கலாம்.',
        ],
        [
            'en_q' => 'Is there any timeline to reopen my account?',
            'ta_q' => 'எனது கணக்கை மீண்டும் திறக்க கால கெடு இருக்கிறதா?',
            'en_a' => 'You can reopen your account if you have not crossed 6 months from the registered date and if you have pending download limits. Else you have to renew your profile.',
            'ta_a' => 'நீங்கள் பதிவுசெய்த தேதியிலிருந்து 6 மாதங்களைத் தாண்டவில்லை என்றால், பதிவிறக்க வரம்புகள் நிலுவையில் இருந்தால் உங்கள் கணக்கை மீண்டும் திறக்கலாம். இல்லையெனில் உங்கள் சுயவிவரத்தை புதுப்பிக்க வேண்டும்.',
        ],
        [
            'en_q' => 'Will I be allowed to edit my profile after registration?',
            'ta_q' => 'பதிவுசெய்த பிறகு எனது சுயவிவரத்தைத் திருத்த அனுமதிக்கப்படுமா?',
            'en_a' => 'Yes, you are allowed to edit your profile for 7 days from the date of registration.',
            'ta_a' => 'ஆம், பதிவுசெய்த நாளிலிருந்து 7 நாட்களுக்கு உங்கள் சுயவிவரத்தைத் திருத்த அனுமதிக்கப்படுவீர்கள்.',
        ],
    ],

    'offline' => [
        [
            'en_q' => 'Will i be able to view other profiles in the site?',
            'ta_q' => 'தளத்தின் பிற சுயவிவரங்களை என்னால் காண முடியுமா?',
            'en_a' => 'Yes, you can see other profiles in the site, however you will be allowed to see limited information only.',
            'ta_a' => 'ஆம், நீங்கள் தளத்தில் பிற சுயவிவரங்களைக் காணலாம், இருப்பினும் வரையறுக்கப்பட்ட தகவல்களைக் காண நீங்கள் அனுமதிக்கப்படுவீர்கள்.',
        ],
        [
            'en_q' => 'Will I be allowed to edit my profile after registration?',
            'ta_q' => 'பதிவுசெய்த பிறகு எனது சுயவிவரத்தைத் திருத்த அனுமதிப்பீர்களா?',
            'en_a' => 'Yes, you are allowed to edit your profile for 7 days from the date of registration.',
            'ta_a' => 'ஆம், பதிவுசெய்த நாளிலிருந்து 7 நாட்களுக்கு உங்கள் சுயவிவரத்தைத் திருத்த அனுமதிக்கப்படுவீர்கள்.',
        ],
        [
            'en_q' => 'What are the features available for me since I have done my registration offline?',
            'ta_q' => 'எனது பதிவை ஆஃப்லைனில் செய்ததிலிருந்து எனக்கு கிடைக்கும் அம்சங்கள் யாவை?',
            'en_a' => 'You will be able to see the limited details of all the profiles available in the website. You can also shortlist profiles if required.',
            'ta_a' => 'இணையதளத்தில் கிடைக்கும் அனைத்து சுயவிவரங்களின் வரையறுக்கப்பட்ட விவரங்களை நீங்கள் காண முடியும். தேவைப்பட்டால் சுயவிவரத்தை குறுகிய பட்டியலிடலாம்.',
        ],
        [
            'en_q' => 'Will i be able to express my interest?',
            'ta_q' => 'எனது ஆர்வத்தை என்னால் வெளிப்படுத்த முடியுமா?',
            'en_a' => 'No, only online registered members can avail this feature.',
            'ta_a' => 'இல்லை, ஆன்லைனில் பதிவுசெய்யப்பட்ட உறுப்பினர்கள் மட்டுமே இந்த அம்சத்தைப் பெற முடியும்.',
        ],
        [
            'en_q' => 'Will i be able to upload my picture?',
            'ta_q' => 'எனது படத்தை பதிவேற்ற முடியுமா?',
            'en_a' => 'Yes, you can upload only your profile picture.',
            'ta_a' => 'ஆம், உங்கள் சுயவிவரப் படத்தை மட்டுமே பதிவேற்ற முடியும்.',
        ],
        [
            'en_q' => 'Will i be able to download other profiles?',
            'ta_q' => 'நான் மற்ற சுயவிவரத்தைப் பதிவிறக்க முடியுமா?',
            'en_a' => 'No, you will not be able to download others\' profiles unless you are an online registered member.',
            'ta_a' => 'இல்லை, மற்றவர்களின் சுயவிவரத்தை நீங்கள் பதிவிறக்க முடியாது. நீங்கள் ஆன்லைன் பதிவு செய்யப்பட்ட உறுப்பினராக இல்லாவிட்டால்.',
        ],
        [
            'en_q' => 'Will my profile appear in others\' search?',
            'ta_q' => 'மற்றவர்கள் தேடலில் எனது சுயவிவரம் தோன்றுமா?',
            'en_a' => 'Yes, offline registered profile will be visible in the profile search in the active member tab.',
            'ta_a' => 'ஆம், செயலில் உள்ள உறுப்பினர் தாவலில் சுயவிவரத் தேடலில் ஆஃப்லைனில் பதிவுசெய்யப்பட்ட சுயவிவரம் தெரியும்.',
        ],
        [
            'en_q' => 'Why can\'t i message others?',
            'ta_q' => 'நான் ஏன் மற்றவர்களுக்கு செய்தி அனுப்ப முடியாது?',
            'en_a' => 'You can\'t message because you are an offline registered user. However if you register online or upgrade your profile to online, you will be able to use this messaging feature.',
            'ta_a' => 'நீங்கள் ஆஃப்லைனில் பதிவுசெய்த பயனராக இருப்பதால் நீங்கள் செய்தி அனுப்ப முடியாது, இருப்பினும் நீங்கள் ஆன்லைனில் பதிவுசெய்தால் அல்லது உங்கள் சுயவிவரத்தை ஆன்லைனில் மேம்படுத்தினால், இந்த செய்தியிடல் அம்சத்தை நீங்கள் பெற முடியும்.',
        ],
        [
            'en_q' => 'Why can\'t i follow others?',
            'ta_q' => 'நான் ஏன் மற்றவர்களைப் பின்பற்ற முடியாது?',
            'en_a' => 'Only online registered members can follow others. If you register online or upgrade your profile to online, you will be able to use this follow feature.',
            'ta_a' => 'ஆன்லைன் பதிவு செய்யப்பட்ட உறுப்பினர்கள் மட்டுமே மற்றவர்களைப் பின்பற்ற முடியும். நீங்கள் ஆன்லைனில் பதிவுசெய்தால் அல்லது உங்கள் சுயவிவரத்தை ஆன்லைனுக்கு மேம்படுத்தினால், இந்த ஃபோலோ அம்சத்தை நீங்கள் பெற முடியும்.',
        ],
        [
            'en_q' => 'What should i do to see full profile details of the matching profile?',
            'ta_q' => 'பொருந்தும் சுயவிவரத்தின் முழு சுயவிவர விவரங்களைக் காண நான் என்ன செய்ய வேண்டும்?',
            'en_a' => 'By visiting the forum on working days you can get the full profile details, or you can upgrade your profile to online to see the full profile online.',
            'ta_a' => 'வேலை நாட்களில் மன்றத்தைப் பார்வையிடுவதன் மூலம் நீங்கள் முழு சுயவிவர விவரங்களைப் பெறலாம் அல்லது ஆன்லைனில் முழு சுயவிவரத்தைக் காண ஆன்லைனில் உங்கள் சுயவிவரத்தை மேம்படுத்தலாம்.',
        ],
        [
            'en_q' => 'How can i become an online registered member?',
            'ta_q' => 'நான் ஆன்லைனில் பதிவுசெய்யப்பட்ட உறுப்பினராக எப்படி மாற முடியும்?',
            'en_a' => 'By paying the online registration fee, you can upgrade your profile to access all the features available for online members.',
            'ta_a' => 'ஆன்லைன் பதிவு கட்டணத்தை செலுத்துவதன் மூலம், ஆன்லைன் உறுப்பினர்களுக்குக் கிடைக்கும் அனைத்து அம்சங்களையும் பெற உங்கள் சுயவிவரத்தை ஆன்லைன் சுயவிவரமாக மேம்படுத்தலாம்.',
        ],
        [
            'en_q' => 'Will i be able to see other\'s profile if i have registered in forum?',
            'ta_q' => 'நான் மன்றத்தில் பதிவு செய்திருந்தால் மற்றவர்களின் சுயவிவரத்தைக் காண முடியுமா?',
            'en_a' => 'Yes, you will be able to see other profiles in the forum itself on all working days.',
            'ta_a' => 'ஆம், எல்லா வேலை நாட்களிலும் நீங்கள் மன்றத்தில் பிற சுயவிவரங்களைக் காண முடியும்.',
        ],
        [
            'en_q' => 'Will i be able to see my profile in online if i have registered directly in the forum?',
            'ta_q' => 'நான் மன்றத்தில் நேரடியாக பதிவு செய்திருந்தால் எனது சுயவிவரத்தை ஆன்லைனில் காண முடியுமா?',
            'en_a' => 'Yes, you will be able to see your profile.',
            'ta_a' => 'ஆம், உங்கள் சுயவிவரத்தைக் காண முடியும்.',
        ],
        [
            'en_q' => 'Will my profile appear in others\' search if i have registered directly in the forum?',
            'ta_q' => 'நான் மன்றத்தில் நேரடியாக பதிவு செய்திருந்தால் எனது சுயவிவரம் மற்றவர்களின் தேடலில் தோன்றும்?',
            'en_a' => 'Yes, your profile will appear in others\' search.',
            'ta_a' => 'ஆம், உங்கள் சுயவிவரம் மற்றவர்களின் தேடலில் தோன்றும்.',
        ],
        [
            'en_q' => 'How long will my profile be visible in the site if i have registered directly in the forum?',
            'ta_q' => 'மன்றத்தில் நான் நேரடியாக பதிவு செய்திருந்தால், எனது சுயவிவரம் எவ்வளவு காலம் தளத்தில் தெரியும்?',
            'en_a' => 'Your profile will be active for 6 months and visible in other members\' search for the same duration. After the validity expires, the profile will be deactivated.',
            'ta_a' => 'உங்கள் சுயவிவரம் 6 மாதங்களுக்கு செயலில் இருக்கும், மற்ற உறுப்பினர்களின் தேடலில் அதே காலத்திற்கு தெரியும். செல்லுபடியாகும் காலம் முடிந்த பிறகு சுயவிவரம் செயலிழக்கப்படும்.',
        ],
        [
            'en_q' => 'Will i be able to access any profile after 6 months without renewing?',
            'ta_q' => 'புதுப்பிக்காமல் 6 மாதங்களுக்குப் பிறகு எந்த சுயவிவரத்தையும் பெற முடியுமா?',
            'en_a' => 'No, you will not be able to access any profile unless you renew your profile.',
            'ta_a' => 'இல்லை, உங்கள் சுயவிவரத்தை புதுப்பிக்காவிட்டால் எந்த சுயவிவரத்தையும் பெற முடியாது.',
        ],
        [
            'en_q' => 'If i want to register directly in the forum, what should i do?',
            'ta_q' => 'நான் மன்றத்தில் நேரடியாக பதிவு செய்ய விரும்பினால் நான் என்ன செய்ய வேண்டும்?',
            'en_a' => 'You can visit the forum directly on working days and register your profile.',
            'ta_a' => 'வேலை நாட்களில் நீங்கள் நேரடியாக மன்றத்தைப் பார்வையிடலாம் மற்றும் உங்கள் சுயவிவரத்தை பதிவு செய்யலாம்.',
        ],
    ],
];
